[lint]
ignore = [
	"DTZ001",
	"DTZ002",
	"DTZ006",
	"DTZ007",
	"DTZ011",
	"DTZ901",
    "S112",
    "BLE001",
    "B008",  # FIXME
    "B020",
    "LOG015",
    "SIM102",
    "SIM114",
    "SIM117",
    "I",  # FIXME
    "F401",
    "F821",  # FIXME
    "F841",
    "D",
    "PLR1704",
    "PLR1730",
    "PLW1510",
    "RUF059",
    "TRY002",
]
